spring:
  profiles:
    active: dev #激发开发环境配置
---
server:
  port: 8001
mybatis:
  config-location: classpath:com/mengxuegu/springcloud/mapper/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.springcloud.entities
spring:
  profiles: dev #开发环境
  application:
    name: microservice-product-config-newbus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    
emp:
  name:zhangsan
 
---
server:
  port: 8001
mybatis:
  config-location: classpath:com/mengxuegu/springcloud/mapper/mybatis.cfg.xml
  type-aliases-package: com.mengxuegu.springcloud.entities # 所有Entity别名类所在包
#  mapper-locations: classpath:mapper/mapper/**/*.xml     # mapper映射文件

spring:
  profiles: prod  #生产环境
  application:
    name: microservice-product-config

  datasource:
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true   #服务发现开关
    serviceUrl:    #客户端（服务提供者）注册到哪一个Eureka Server服务注册中心，多个用逗号隔开
      defaultZone : http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka

  instance:
    instanceId: ${spring.application.name}:${server.port}  #指定实例id就不会显示主机名
    prefer-ip-address: true  #访问路径可以显示ip地址
